development:
  adapter: postgresql
  database: nathanielnathaniel_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: nathanielnathaniel_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: nathanielnathaniel_production
  pool: 5
  timeout: 5000
